/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;

import Negocio.Area_Proceso;
import Negocio.Evaluacion_Area_Proceso;
import Negocio.Instancia;
import Negocio.Objetivo;
import Negocio.Practica;
import Negocio.VariablesGoblales;
import Presentacion.Frm_Principal;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author Usuario
 */
public class Pnl_Evaluacion_Area_Proceso extends javax.swing.JPanel {

    public Area_Proceso ap;

    public Evaluacion_Area_Proceso eap;

    /**
     * Creates new form Pnl_home
     */
    public Pnl_Evaluacion_Area_Proceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_descripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_valoracion_sugerida = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jCheckBox_fuera_de_alcance = new javax.swing.JCheckBox();
        jCheckBox_sin_evaluacion_objetiva = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_valoracion_elegida = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Evaluacion  Area de Proceso");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 8, 194, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        jLabel_titulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_titulo.setText("Area Proceso# : titulo");
        jPanel1.add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 320, -1));

        jTextArea_descripcion.setColumns(20);
        jTextArea_descripcion.setRows(5);
        jScrollPane1.setViewportView(jTextArea_descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 490, 240));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Valoracion elegida:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jComboBox_valoracion_sugerida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SATISFECHA", "INSATISFECHA", "NO APLICABLE", "SIN PUNTAJE" }));
        jPanel1.add(jComboBox_valoracion_sugerida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 140, 30));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 110, -1));

        jCheckBox_fuera_de_alcance.setText("Fuera de alcance");
        jPanel1.add(jCheckBox_fuera_de_alcance, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 140, -1));

        jCheckBox_sin_evaluacion_objetiva.setText("Sin evaluacion objetiva");
        jPanel1.add(jCheckBox_sin_evaluacion_objetiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 170, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Valoracion sugerida:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

        jComboBox_valoracion_elegida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SATISFECHA", "INSATISFECHA", "NO APLICABLE", "SIN PUNTAJE" }));
        jPanel1.add(jComboBox_valoracion_elegida, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 130, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int i = 0; i < ap.getListaObjetivosEspecificos().size(); i++) {
            Objetivo o = ap.getListaObjetivosEspecificos().get(i);
            if (o.getId_evaluacion_objetivo() != 0) {
                for (int j = 0; j < o.getListaPracticas().size(); j++) {
                    Practica practica = o.getListaPracticas().get(j);
                    if (practica.getId_evaluacion_practiva() != 0) {
                        for (int k = 0; k < practica.getListaInstancia().size(); k++) {
                            Instancia instancia = practica.getListaInstancia().get(k);
                            if (instancia.getId_evaluacion_practica() == 0) {
                                String message = "Tiene elementos pendiente de evaluacion.";
                                JOptionPane.showMessageDialog(null, message, "Toast", JOptionPane.INFORMATION_MESSAGE);
                                return;
                            }
                        }

                    } else {
                        String message = "Tiene elementos pendiente de evaluacion.";
                        JOptionPane.showMessageDialog(null, message, "Toast", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                }
            } else {
                String message = "Tiene elementos pendiente de evaluacion.";
                JOptionPane.showMessageDialog(null, message, "Toast", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

        
         for (int i = 0; i < ap.getListaObjetivosGenericos().size(); i++) {
            Objetivo o = ap.getListaObjetivosGenericos().get(i);
            if (o.getId_evaluacion_objetivo() != 0) {
                for (int j = 0; j < o.getListaPracticas().size(); j++) {
                    Practica practica = o.getListaPracticas().get(j);
                    if (practica.getId_evaluacion_practiva() != 0) {
                        for (int k = 0; k < practica.getListaInstancia().size(); k++) {
                            Instancia instancia = practica.getListaInstancia().get(k);
                            if (instancia.getId_evaluacion_practica() == 0) {
                                String message = "Tiene elementos pendiente de evaluacion.";
                                JOptionPane.showMessageDialog(null, message, "Toast", JOptionPane.INFORMATION_MESSAGE);
                                return;
                            }
                        }

                    } else {
                        String message = "Tiene elementos pendiente de evaluacion.";
                        JOptionPane.showMessageDialog(null, message, "Toast", JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                }
            } else {
                String message = "Tiene elementos pendiente de evaluacion.";
                JOptionPane.showMessageDialog(null, message, "Toast", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
         
         
         
         
         
        int cant = Frm_Principal.archivo.getListaEvaluacionAreaProcesos().size();
        int FA = 0;
        if (jCheckBox_fuera_de_alcance.isSelected()) {
            FA = 1;
        } else {
            FA = 0;
        }

        int SEO = 0;
        if (jCheckBox_sin_evaluacion_objetiva.isSelected()) {
            SEO = 1;
        } else {
            SEO = 0;
        }

        int VS = jComboBox_valoracion_sugerida.getSelectedIndex();
        int VE = jComboBox_valoracion_elegida.getSelectedIndex();
        eap = new Evaluacion_Area_Proceso(cant + 1, jLabel_titulo.getText(), jTextArea_descripcion.getText(), FA, SEO, VS, VE);
        Frm_Principal.archivo.getListaEvaluacionAreaProcesos().add(eap);
        ap.setId_evaluacion_area_proceso(cant + 1);

        System.out.println("INNN:" + ap.getId_evaluacion_area_proceso());
        System.out.println("pu:" + (VariablesGoblales.puntero - 1));
        marcarNodoRecursivamente(ap.getNombre_area_proceso());
    }//GEN-LAST:event_jButton1ActionPerformed
    private void marcarNodoRecursivamente(String textoNodo) {
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) Frm_Principal.jTree_Arbol.getModel().getRoot();
        DefaultMutableTreeNode nodo = buscarNodo(raiz, textoNodo);
        if (nodo != null) {
            nodo.setUserObject("✅" + nodo.getUserObject());
            ((DefaultTreeModel) Frm_Principal.jTree_Arbol.getModel()).nodeChanged(nodo);
        }
    }

    private DefaultMutableTreeNode buscarNodo(DefaultMutableTreeNode raiz, String textoNodo) {
        TreePath selectedPath = new TreePath(raiz.getPath());
        boolean isSelected = Frm_Principal.jTree_Arbol.isPathSelected(selectedPath);
        System.out.println("sw=" + isSelected);
        if ((raiz.getUserObject().toString().equals(textoNodo)) && isSelected) {
            return raiz;
        } else {
            for (int i = 0; i < raiz.getChildCount(); i++) {
                DefaultMutableTreeNode encontrado = buscarNodo((DefaultMutableTreeNode) raiz.getChildAt(i), textoNodo);
                if (encontrado != null) {
                    return encontrado;
                }
            }
            return null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox_fuera_de_alcance;
    private javax.swing.JCheckBox jCheckBox_sin_evaluacion_objetiva;
    private javax.swing.JComboBox<String> jComboBox_valoracion_elegida;
    public static javax.swing.JComboBox<String> jComboBox_valoracion_sugerida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea_descripcion;
    // End of variables declaration//GEN-END:variables
}
